/** 판매하기 등에서 쓰는 제조사별 차량 모델 (한국 중고부품 시장 기준, 최근 모델 우선) */

export type VehicleModelOption = { id: string; label: string };

export const VEHICLE_MODELS: Record<string, VehicleModelOption[]> = {
  hyundai: [
    { id: "ioniq9", label: "아이오닉9" },
    { id: "ioniq5", label: "아이오닉5" },
    { id: "ioniq5-n", label: "아이오닉5 N" },
    { id: "ioniq6", label: "아이오닉6" },
    { id: "ioniq6-n", label: "아이오닉6 N" },
    { id: "casper-electric", label: "캐스퍼 일렉트릭" },
    { id: "staria-ev", label: "스타리아 EV" },
    { id: "kona-electric", label: "코나 일렉트릭" },
    { id: "avante", label: "아반떼" },
    { id: "sonata", label: "쏘나타" },
    { id: "grandeur", label: "그랜저" },
    { id: "casper", label: "캐스퍼" },
    { id: "kona", label: "코나" },
    { id: "venue", label: "베뉴" },
    { id: "tucson", label: "투싼" },
    { id: "santafe", label: "싼타페" },
    { id: "palisade", label: "팰리세이드" },
    { id: "staria", label: "스타리아" },
    { id: "nexo", label: "넥쏘" },
    { id: "ioniq", label: "아이오닉" },
    { id: "porter-electric", label: "포터 일렉트릭" },
    { id: "porter", label: "포터" },
    { id: "st1", label: "ST1" },
    { id: "accent", label: "엑센트" },
    { id: "i30", label: "i30" },
    { id: "veloster", label: "벨로스터" },
    { id: "maxcruz", label: "맥스크루즈" },
    { id: "veracruz", label: "베라크루즈" },
    { id: "starex", label: "스타렉스" },
    { id: "solati", label: "쏠라티" },
    { id: "mighty", label: "마이티" },
    { id: "genesis-coupe", label: "제네시스 쿠페" },
    { id: "equus", label: "에쿠스" },
    { id: "santa-cruz", label: "싼타크루즈" },
  ],
  kia: [
    { id: "ev3", label: "EV3" },
    { id: "ev4", label: "EV4" },
    { id: "ev5", label: "EV5" },
    { id: "ev6", label: "EV6" },
    { id: "ev9", label: "EV9" },
    { id: "syros", label: "시로스" },
    { id: "tasman", label: "타스만" },
    { id: "pv5", label: "PV5" },
    { id: "morning", label: "모닝" },
    { id: "ray", label: "레이" },
    { id: "k3", label: "K3" },
    { id: "k5", label: "K5" },
    { id: "k8", label: "K8" },
    { id: "k9", label: "K9" },
    { id: "seltos", label: "셀토스" },
    { id: "niro", label: "니로" },
    { id: "sportage", label: "스포티지" },
    { id: "sorento", label: "쏘렌토" },
    { id: "carnival", label: "카니발" },
    { id: "mohave", label: "모하비" },
    { id: "stonic", label: "스토닉" },
    { id: "soul", label: "쏘울" },
    { id: "bongo", label: "봉고" },
    { id: "pride", label: "프라이드" },
    { id: "k7", label: "K7" },
    { id: "forte", label: "포르테" },
    { id: "cerato", label: "세라토" },
    { id: "lotze", label: "로체" },
    { id: "opirus", label: "오피러스" },
    { id: "sedona", label: "세드나" },
    { id: "carens", label: "카렌스" },
    { id: "telluride", label: "텔루라이드" },
  ],
  genesis: [
    { id: "gv90", label: "GV90" },
    { id: "g70", label: "G70" },
    { id: "g70-shooting-brake", label: "G70 슈팅브레이크" },
    { id: "g80", label: "G80" },
    { id: "electrified-g80", label: "Electrified G80" },
    { id: "g90", label: "G90" },
    { id: "gv60", label: "GV60" },
    { id: "gv70", label: "GV70" },
    { id: "electrified-gv70", label: "Electrified GV70" },
    { id: "gv80", label: "GV80" },
    { id: "gv80-coupe", label: "GV80 쿠페" },
  ],
  chevrolet: [
    { id: "trax-crossover", label: "트랙스 크로스오버" },
    { id: "trailblazer", label: "트레일블레이저" },
    { id: "equinox", label: "이쿼녹스" },
    { id: "traverse", label: "트래버스" },
    { id: "colorado", label: "콜로라도" },
    { id: "tahoe", label: "타호" },
    { id: "suburban", label: "서브어반" },
    { id: "bolt-ev", label: "볼트 EV" },
    { id: "bolt-euv", label: "볼트 EUV" },
    { id: "spark", label: "스파크" },
    { id: "trax", label: "트랙스" },
    { id: "aveo", label: "아베오" },
    { id: "cruze", label: "크루즈" },
    { id: "malibu", label: "말리부" },
    { id: "impala", label: "임팔라" },
    { id: "alpheon", label: "알페온" },
    { id: "orlando", label: "올란도" },
    { id: "captiva", label: "캡티바" },
    { id: "camaro", label: "카마로" },
    { id: "corvette", label: "콜벳" },
  ],
  kgm: [
    { id: "musso-ev", label: "무쏘 EV" },
    { id: "musso-sports", label: "무쏘 스포츠" },
    { id: "musso-khan", label: "무쏘 칸" },
    { id: "torres", label: "토레스" },
    { id: "torres-evx", label: "토레스 EVX" },
    { id: "actyon", label: "액티언" },
    { id: "tivoli", label: "티볼리" },
    { id: "korando", label: "코란도" },
    { id: "rexton", label: "렉스턴" },
    { id: "rexton-sports", label: "렉스턴 스포츠" },
    { id: "korando-sports", label: "코란도 스포츠" },
    { id: "actyon-sports", label: "액티언 스포츠" },
    { id: "musso", label: "무쏘" },
    { id: "chairman", label: "체어맨" },
    { id: "kyron", label: "카이런" },
  ],
  renault: [
    { id: "grand-koleos", label: "그랑 콜레오스" },
    { id: "arkana", label: "아르카나" },
    { id: "xm3", label: "XM3" },
    { id: "qm6", label: "QM6" },
    { id: "sm6", label: "SM6" },
    { id: "master", label: "마스터" },
    { id: "sm3", label: "SM3" },
    { id: "sm5", label: "SM5" },
    { id: "sm7", label: "SM7" },
    { id: "qm3", label: "QM3" },
    { id: "qm5", label: "QM5" },
    { id: "clio", label: "클리오" },
    { id: "captur", label: "캡처" },
    { id: "twizy", label: "트위지" },
  ],
  bmw: [
    { id: "xm", label: "XM" },
    { id: "ix2", label: "iX2" },
    { id: "ix1", label: "iX1" },
    { id: "ix3", label: "iX3" },
    { id: "ix", label: "iX" },
    { id: "i4", label: "i4" },
    { id: "i5", label: "i5" },
    { id: "i7", label: "i7" },
    { id: "1series", label: "1시리즈" },
    { id: "2series", label: "2시리즈" },
    { id: "3series", label: "3시리즈" },
    { id: "4series", label: "4시리즈" },
    { id: "5series", label: "5시리즈" },
    { id: "6series", label: "6시리즈" },
    { id: "7series", label: "7시리즈" },
    { id: "8series", label: "8시리즈" },
    { id: "x1", label: "X1" },
    { id: "x2", label: "X2" },
    { id: "x3", label: "X3" },
    { id: "x4", label: "X4" },
    { id: "x5", label: "X5" },
    { id: "x6", label: "X6" },
    { id: "x7", label: "X7" },
    { id: "z4", label: "Z4" },
    { id: "i3", label: "i3" },
    { id: "m2", label: "M2" },
    { id: "m3", label: "M3" },
    { id: "m4", label: "M4" },
    { id: "m5", label: "M5" },
  ],
  benz: [
    { id: "cle", label: "CLE" },
    { id: "eqe-suv", label: "EQE SUV" },
    { id: "eqs-suv", label: "EQS SUV" },
    { id: "eqa", label: "EQA" },
    { id: "eqb", label: "EQB" },
    { id: "eqc", label: "EQC" },
    { id: "eqe", label: "EQE" },
    { id: "eqs", label: "EQS" },
    { id: "a-class", label: "A클래스" },
    { id: "b-class", label: "B클래스" },
    { id: "c-class", label: "C클래스" },
    { id: "e-class", label: "E클래스" },
    { id: "s-class", label: "S클래스" },
    { id: "maybach-s", label: "마이바흐 S클래스" },
    { id: "cla", label: "CLA" },
    { id: "cls", label: "CLS" },
    { id: "gla", label: "GLA" },
    { id: "glb", label: "GLB" },
    { id: "glc", label: "GLC" },
    { id: "gle", label: "GLE" },
    { id: "gls", label: "GLS" },
    { id: "maybach-gls", label: "마이바흐 GLS" },
    { id: "g-class", label: "G클래스" },
    { id: "sl", label: "SL" },
    { id: "slc", label: "SLC" },
    { id: "amg-gt", label: "AMG GT" },
    { id: "vito", label: "비토" },
    { id: "sprinter", label: "스프린터" },
    { id: "v-class", label: "V클래스" },
  ],
  audi: [
    { id: "q6-etron", label: "Q6 e-tron" },
    { id: "a6-etron", label: "A6 e-tron" },
    { id: "sq6-etron", label: "SQ6 e-tron" },
    { id: "q4-etron", label: "Q4 e-tron" },
    { id: "etron-gt", label: "e-tron GT" },
    { id: "a1", label: "A1" },
    { id: "a3", label: "A3" },
    { id: "a4", label: "A4" },
    { id: "a5", label: "A5" },
    { id: "a6", label: "A6" },
    { id: "a7", label: "A7" },
    { id: "a8", label: "A8" },
    { id: "q2", label: "Q2" },
    { id: "q3", label: "Q3" },
    { id: "q5", label: "Q5" },
    { id: "q7", label: "Q7" },
    { id: "q8", label: "Q8" },
    { id: "tt", label: "TT" },
    { id: "r8", label: "R8" },
    { id: "etron", label: "e-tron" },
    { id: "rs3", label: "RS3" },
    { id: "rs4", label: "RS4" },
    { id: "rs5", label: "RS5" },
    { id: "rs6", label: "RS6" },
    { id: "rs7", label: "RS7" },
  ],
  volkswagen: [
    { id: "atlas", label: "아틀라스" },
    { id: "tayron", label: "타이론" },
    { id: "id4", label: "ID.4" },
    { id: "id5", label: "ID.5" },
    { id: "id6", label: "ID.6" },
    { id: "id-buzz", label: "ID.버즈" },
    { id: "id3", label: "ID.3" },
    { id: "tiguan", label: "티구안" },
    { id: "touareg", label: "투아렉" },
    { id: "t-roc", label: "티록" },
    { id: "golf", label: "골프" },
    { id: "polo", label: "폴로" },
    { id: "jetta", label: "제타" },
    { id: "passat", label: "파사트" },
    { id: "arteon", label: "아테온" },
    { id: "beetle", label: "비틀" },
    { id: "scirocco", label: "시로코" },
    { id: "cc", label: "CC" },
    { id: "transporter", label: "트랜스포터" },
    { id: "caddy", label: "캐디" },
  ],
  porsche: [
    { id: "macan-electric", label: "마칸 일렉트릭" },
    { id: "cayenne-electric", label: "카이엔 일렉트릭" },
    { id: "taycan", label: "타이칸" },
    { id: "911", label: "911" },
    { id: "718-cayman", label: "718 박스터" },
    { id: "718-cayman", label: "718 카이맨" },
    { id: "panamera", label: "파나메라" },
    { id: "cayenne", label: "카이엔" },
    { id: "macan", label: "마칸" },
  ],
  mini: [
    { id: "ace-man", label: "에이스맨" },
    { id: "electric", label: "일렉트릭 (쿠퍼 SE)" },
    { id: "hatch", label: "해치 (3도어/5도어)" },
    { id: "clubman", label: "클럽맨" },
    { id: "countryman", label: "컨트리맨" },
    { id: "convertible", label: "컨버터블" },
    { id: "paceman", label: "페이스맨" },
    { id: "coupe", label: "쿠페" },
    { id: "roadster", label: "로드스터" },
  ],
  volvo: [
    { id: "ex30", label: "EX30" },
    { id: "ex90", label: "EX90" },
    { id: "em90", label: "EM90" },
    { id: "ec40", label: "EC40" },
    { id: "c40", label: "C40" },
    { id: "xc40", label: "XC40" },
    { id: "xc60", label: "XC60" },
    { id: "xc90", label: "XC90" },
    { id: "s60", label: "S60" },
    { id: "s90", label: "S90" },
    { id: "v60", label: "V60" },
    { id: "v90", label: "V90" },
  ],
  jaguar: [
    { id: "i-pace", label: "I-PACE" },
    { id: "f-pace", label: "F-PACE" },
    { id: "e-pace", label: "E-PACE" },
    { id: "f-type", label: "F-TYPE" },
    { id: "xe", label: "XE" },
    { id: "xf", label: "XF" },
    { id: "xj", label: "XJ" },
  ],
  landrover: [
    { id: "defender", label: "디펜더" },
    { id: "range-rover", label: "레인지로버" },
    { id: "range-rover-sport", label: "레인지로버 스포츠" },
    { id: "range-rover-velar", label: "레인지로버 벨라" },
    { id: "range-rover-evoque", label: "레인지로버 이보크" },
    { id: "discovery", label: "디스커버리" },
    { id: "discovery-sport", label: "디스커버리 스포츠" },
  ],
  toyota: [
    { id: "bZ4X", label: "bZ4X" },
    { id: "crown", label: "크라운" },
    { id: "camry", label: "캠리" },
    { id: "prius", label: "프리우스" },
    { id: "rav4", label: "RAV4" },
    { id: "highlander", label: "하이랜더" },
    { id: "sienna", label: "시에나" },
    { id: "alphard", label: "알파드" },
    { id: "vellfire", label: "벨파이어" },
    { id: "land-cruiser", label: "랜드크루저" },
    { id: "prado", label: "프라도" },
    { id: "hilux", label: "하이럭스" },
    { id: "yaris", label: "야리스" },
    { id: "corolla", label: "코롤라" },
    { id: "avalon", label: "아발론" },
    { id: "c-hr", label: "C-HR" },
    { id: "86", label: "86" },
    { id: "supra", label: "수프라" },
  ],
  lexus: [
    { id: "lbx", label: "LBX" },
    { id: "lm", label: "LM" },
    { id: "tx", label: "TX" },
    { id: "rz", label: "RZ" },
    { id: "ux", label: "UX" },
    { id: "nx", label: "NX" },
    { id: "rx", label: "RX" },
    { id: "gx", label: "GX" },
    { id: "lx", label: "LX" },
    { id: "is", label: "IS" },
    { id: "es", label: "ES" },
    { id: "gs", label: "GS" },
    { id: "ls", label: "LS" },
    { id: "ct", label: "CT" },
    { id: "rc", label: "RC" },
    { id: "lc", label: "LC" },
  ],
  honda: [
    { id: "prologue", label: "프롤로그" },
    { id: "zr-v", label: "ZR-V" },
    { id: "civic", label: "시빅" },
    { id: "accord", label: "어코드" },
    { id: "cr-v", label: "CR-V" },
    { id: "hr-v", label: "HR-V" },
    { id: "pilot", label: "파일럿" },
    { id: "odyssey", label: "오딧세이" },
    { id: "fit", label: "핏" },
    { id: "insight", label: "인사이트" },
    { id: "ridgeline", label: "리지라인" },
    { id: "nsx", label: "NSX" },
    { id: "s2000", label: "S2000" },
    { id: "e", label: "Honda e" },
  ],
  nissan: [
    { id: "ariya", label: "아리야" },
    { id: "sakura", label: "사쿠라" },
    { id: "leaf", label: "리프" },
    { id: "qashqai", label: "캐시카이" },
    { id: "x-trail", label: "엑스트레일" },
    { id: "pathfinder", label: "패스파인더" },
    { id: "patrol", label: "패트롤" },
    { id: "navara", label: "나바라" },
    { id: "serena", label: "세레나" },
    { id: "altima", label: "알티마" },
    { id: "maxima", label: "맥시마" },
    { id: "juke", label: "쥬크" },
    { id: "march", label: "마치" },
    { id: "tiida", label: "티다" },
    { id: "sentra", label: "센트라" },
    { id: "350z", label: "350Z" },
    { id: "370z", label: "370Z" },
    { id: "gt-r", label: "GT-R" },
  ],
  infiniti: [
    { id: "qx50", label: "QX50" },
    { id: "qx55", label: "QX55" },
    { id: "qx60", label: "QX60" },
    { id: "qx80", label: "QX80" },
    { id: "q50", label: "Q50" },
    { id: "q60", label: "Q60" },
    { id: "q70", label: "Q70" },
    { id: "g37", label: "G37" },
    { id: "m37", label: "M37" },
    { id: "fx35", label: "FX35" },
    { id: "fx37", label: "FX37" },
  ],
  mazda: [
    { id: "cx-60", label: "CX-60" },
    { id: "cx-70", label: "CX-70" },
    { id: "cx-80", label: "CX-80" },
    { id: "cx-90", label: "CX-90" },
    { id: "cx-30", label: "CX-30" },
    { id: "cx-5", label: "CX-5" },
    { id: "cx-50", label: "CX-50" },
    { id: "cx-3", label: "CX-3" },
    { id: "cx-8", label: "CX-8" },
    { id: "cx-9", label: "CX-9" },
    { id: "mazda3", label: "마즈다3" },
    { id: "mazda6", label: "마즈다6" },
    { id: "mazda2", label: "마즈다2" },
    { id: "mx-5", label: "MX-5" },
  ],
  subaru: [
    { id: "solterra", label: "솔테라" },
    { id: "crosstrek", label: "크로스트레크" },
    { id: "forester", label: "포레스터" },
    { id: "outback", label: "아웃백" },
    { id: "ascent", label: "어센트" },
    { id: "impreza", label: "임프레자" },
    { id: "legacy", label: "레거시" },
    { id: "xv", label: "XV" },
    { id: "brz", label: "BRZ" },
    { id: "wrx", label: "WRX" },
    { id: "wrx-sti", label: "WRX STI" },
  ],
  mitsubishi: [
    { id: "outlander-phev", label: "아웃랜더 PHEV" },
    { id: "outlander", label: "아웃랜더" },
    { id: "eclipse-cross", label: "이클립스 크로스" },
    { id: "asx", label: "ASX" },
    { id: "triton", label: "트라이톤" },
    { id: "pajero", label: "파제로" },
    { id: "pajero-sport", label: "파제로 스포츠" },
    { id: "outlander-sport", label: "아웃랜더 스포츠" },
    { id: "mirage", label: "미라지" },
    { id: "lancer", label: "랜서" },
    { id: "attrage", label: "아트라주" },
  ],
  suzuki: [
    { id: "jimny", label: "짐니" },
    { id: "swift", label: "스위프트" },
    { id: "vitara", label: "비타라" },
    { id: "s-cross", label: "S-크로스" },
    { id: "ignis", label: "이그니스" },
    { id: "baleno", label: "발레노" },
    { id: "ciaz", label: "시아즈" },
    { id: "alto", label: "알토" },
  ],
  ford: [
    { id: "mustang-mach-e", label: "머스탱 마하-E" },
    { id: "bronco", label: "브롱코" },
    { id: "bronco-sport", label: "브롱코 스포츠" },
    { id: "explorer", label: "익스플로러" },
    { id: "ranger", label: "레인저" },
    { id: "f-150", label: "F-150" },
    { id: "mustang", label: "머스탱" },
    { id: "escape", label: "이스케이프" },
    { id: "kuga", label: "쿠가" },
    { id: "edge", label: "엣지" },
    { id: "expedition", label: "익스페디션" },
    { id: "transit", label: "트랜짓" },
    { id: "fiesta", label: "피에스타" },
    { id: "focus", label: "포커스" },
    { id: "mondeo", label: "몬데오" },
    { id: "fusion", label: "퓨전" },
  ],
  lincoln: [
    { id: "nautilus", label: "노틸러스" },
    { id: "aviator", label: "에비에이터" },
    { id: "navigator", label: "네비게이터" },
    { id: "corsair", label: "코세어" },
    { id: "mkz", label: "MKZ" },
    { id: "continental", label: "컨티넨탈" },
  ],
  jeep: [
    { id: "avenger", label: "어벤저" },
    { id: "wagoneer", label: "왜고니어" },
    { id: "grand-wagoneer", label: "그랜드 왜고니어" },
    { id: "wrangler", label: "랭글러" },
    { id: "gladiator", label: "글래디에이터" },
    { id: "grand-cherokee", label: "그랜드 체로키" },
    { id: "compass", label: "컴패스" },
    { id: "renegade", label: "레니게이드" },
    { id: "cherokee", label: "체로키" },
    { id: "commander", label: "커맨더" },
  ],
  chrysler: [
    { id: "pacifica", label: "퍼시피카" },
    { id: "voyager", label: "보이저" },
    { id: "300c", label: "300C" },
    { id: "pt-cruiser", label: "PT 크루저" },
  ],
  cadillac: [
    { id: "lyriq", label: "리릭" },
    { id: "optiq", label: "옵틱" },
    { id: "escalade-iq", label: "에스컬레이드 IQ" },
    { id: "ct4", label: "CT4" },
    { id: "ct5", label: "CT5" },
    { id: "ct6", label: "CT6" },
    { id: "xt4", label: "XT4" },
    { id: "xt5", label: "XT5" },
    { id: "xt6", label: "XT6" },
    { id: "escalade", label: "에스컬레이드" },
    { id: "ats", label: "ATS" },
    { id: "cts", label: "CTS" },
  ],
  tesla: [
    { id: "model-y", label: "Model Y" },
    { id: "model-3", label: "Model 3" },
    { id: "model-s", label: "Model S" },
    { id: "model-x", label: "Model X" },
    { id: "cybertruck", label: "사이버트럭" },
  ],
  peugeot: [
    { id: "e-208", label: "e-208" },
    { id: "e-2008", label: "e-2008" },
    { id: "408", label: "408" },
    { id: "508", label: "508" },
    { id: "208", label: "208" },
    { id: "308", label: "308" },
    { id: "2008", label: "2008" },
    { id: "3008", label: "3008" },
    { id: "5008", label: "5008" },
    { id: "partner", label: "파트너" },
    { id: "rifter", label: "리프터" },
  ],
  citroen: [
    { id: "c5-aircross", label: "C5 에어크로스" },
    { id: "c4", label: "C4" },
    { id: "c3", label: "C3" },
    { id: "c5", label: "C5" },
    { id: "berlingo", label: "베를링고" },
    { id: "ds3", label: "DS3" },
    { id: "ds4", label: "DS4" },
    { id: "ds5", label: "DS5" },
    { id: "ds7", label: "DS7" },
  ],
  fiat: [
    { id: "500e", label: "500e" },
    { id: "600e", label: "600e" },
    { id: "500", label: "500" },
    { id: "500x", label: "500X" },
    { id: "panda", label: "판다" },
    { id: "tipo", label: "티포" },
    { id: "doblo", label: "도블로" },
  ],
  ferrari: [
    { id: "12cilindri", label: "12칠린드리" },
    { id: "purosangue", label: "푸로상게" },
    { id: "296", label: "296" },
    { id: "sf90", label: "SF90" },
    { id: "roma", label: "로마" },
    { id: "portofino", label: "포르토피노" },
    { id: "f8", label: "F8" },
    { id: "812", label: "812" },
    { id: "488", label: "488" },
  ],
  lamborghini: [
    { id: "temerario", label: "테메라리오" },
    { id: "revuelto", label: "레부엘토" },
    { id: "urus", label: "우루스" },
    { id: "huracan", label: "우라칸" },
    { id: "aventador", label: "아벤타도르" },
    { id: "gallardo", label: "가야르도" },
  ],
  maserati: [
    { id: "grecale", label: "그레칼레" },
    { id: "mc20", label: "MC20" },
    { id: "granturismo", label: "그란투리스모" },
    { id: "ghibli", label: "기블리" },
    { id: "quattroporte", label: "콰트로포르테" },
    { id: "levante", label: "르반떼" },
  ],
  bentley: [
    { id: "continental-gt", label: "컨티넨탈 GT" },
    { id: "flying-spur", label: "플라잉스퍼" },
    { id: "bentayga", label: "벤테이가" },
    { id: "mulsanne", label: "뮬산" },
  ],
  rollsroyce: [
    { id: "spectre", label: "스펙터" },
    { id: "cullinan", label: "컬리넌" },
    { id: "ghost", label: "고스트" },
    { id: "phantom", label: "팬텀" },
    { id: "wraith", label: "레이스" },
    { id: "dawn", label: "던" },
  ],
  other: [{ id: "other", label: "기타 / 직접 입력" }],
};

export function getVehicleModels(makeId: string): VehicleModelOption[] {
  return VEHICLE_MODELS[makeId] ?? [];
}
